### ISSUE TITLE
使用容器迷你版问题

### ISSUE THREAD

**Issue by xm3good** [SuLingGG/OpenWrt-Docker-Mini#1]
1现在知道的已知道问题
Turbo acc 网络加速全部失效
2ttyd 终端拒绝连接
刚使用 只是看到了两个问题

**Comment by xm3good** [comment]
![16215722176318973325422066612032](https://user-images.githubusercontent.com/21307897/119083260-32e60a80-ba32-11eb-8010-3284e262ff00.jpg)
![Uploading 16215722400648724952245878103567.jpg…]()

**Comment by SuLingGG** [comment]
我 README 里面已经提到了，Docker 版 OpenWrt 与宿主机共享内核。
据我所知， Docker 版 OpenWrt 的 TruboACC 就没有能用的，因为它依赖 offload 或者 fast-classifier 模块，一般宿主机内核都没有或者不默认载入这个模块。如果要解决这个问题，必须要重新编译宿主机的内核。
至于 ttyd，这不是老问题了么...第一次运行 OpenWrt 它都不能用，在“系统 - 启动项 - ttyd” 点一下“重启”那个按钮，重启下 ttyd 服务就好了。
