### ISSUE TITLE
网关无法工作

### ISSUE THREAD

**Issue by r0achnnan9p** [SuLingGG/OpenWrt-Docker-Mini#2]
网关设置为docker里面的openwrt，但是无法访问外网。

但开启梯子以后，可以访问墙后的网站，但依然无法访问无需梯子的IP和网站。

操作系统是树莓派爱好者基地的Debian，带图形界面，设备是树莓派4B。网卡已经开启混杂模式，同时配置了/etc/interfaces中的配置

树莓派日志也看不出什么错误来。

2: eth0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:3a:79:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.50.233/24 brd 192.168.50.255 scope global dynamic noprefixroute eth0
       valid_lft 85737sec preferred_lft 85737sec
    inet6 fe80::a5b4:edf6:f6d9:bd47/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq state DOWN group default qlen 1000
    link/ether dc:a6:32:3a:79:e9 brd ff:ff:ff:ff:ff:ff
4: macvlan@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 9e:26:e9:19:90:6e brd ff:ff:ff:ff:ff:ff
    inet 192.168.50.251/24 brd 192.168.50.255 scope global macvlan
       valid_lft forever preferred_lft forever
    inet6 fe80::9c26:e9ff:fe19:906e/64 scope link
       valid_lft forever preferred_lft forever

**Comment by SuLingGG** [comment]
https://mlapp.cn/1008.html
